name: my_todo_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: '>=2.0.1'
  json_annotation: ^4.8.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
